spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/knittingshop
    username: postgres
    password: Sk3295318
  flyway:
    baseline-on-migrate: true

#debug: true