INSERT INTO compositions (id, title)
values
    (nextval('composition_seq'),'Акриловая'),
    (nextval('composition_seq'),'Альпака'),
    (nextval('composition_seq'),'Ангора'),
    (nextval('composition_seq'),'Бамбук'),
    (nextval('composition_seq'),'Верблюжья'),
    (nextval('composition_seq'),'Вискоза'),
    (nextval('composition_seq'),'Детская'),
    (nextval('composition_seq'),'Для Игрушек'),
    (nextval('composition_seq'),'Кашемир'),
    (nextval('composition_seq'),'Классическая однотонная'),
    (nextval('composition_seq'),'Классическая Фантазийная'),
    (nextval('composition_seq'),'Лен'),
    (nextval('composition_seq'),'Ленточная'),
    (nextval('composition_seq'),'Макраме'),
    (nextval('composition_seq'),'Меринос'),
    (nextval('composition_seq'),'Микрофибра'),
    (nextval('composition_seq'),'Мохер'),
    (nextval('composition_seq'),'Носочная'),
    (nextval('composition_seq'),'Плюшевая'),
    (nextval('composition_seq'),'Полушерсть'),
    (nextval('composition_seq'),'Пух Козий'),
    (nextval('composition_seq'),'Пух Кролика'),
    (nextval('composition_seq'),'Пух Норки'),
    (nextval('composition_seq'),'Пух Норки'),
    (nextval('composition_seq'),'С Люрексом'),
    (nextval('composition_seq'),'С Пайетками'),
    (nextval('composition_seq'),'Твид'),
    (nextval('composition_seq'),'Толстая'),
    (nextval('composition_seq'),'Тонкая'),
    (nextval('composition_seq'),'Травка'),
    (nextval('composition_seq'),'Трикотажная пряжа'),
    (nextval('composition_seq'),'Фактурная однотонная'),
    (nextval('composition_seq'),'Фактурная Фантазийная'),
    (nextval('composition_seq'),'Хлопок'),
    (nextval('composition_seq'),'Целлюлоза'),
    (nextval('composition_seq'),'Шелк'),
    (nextval('composition_seq'),'Шерсть для валяния'),
    (nextval('composition_seq'),'Шерстяная'),
    (nextval('composition_seq'),'Сталь'),
    (nextval('composition_seq'),'Стекло'),
    (nextval('composition_seq'),'Пластик'),
    (nextval('composition_seq'),'Хром');


